import { Prisma } from '@prisma/client';

import { database } from '../../database/client.js';
import { AppError } from '../../errors/app-error.js';

/** Only records belonging to this account are selected. Never export joined users or internal review notes. */
export async function createAccountDataExport(userId: string) {
  return database.$transaction(
    async (tx) => {
      const account = await tx.user.findUnique({
        where: { id: userId },
        select: {
          id: true,
          status: true,
          displayName: true,
          birthDate: true,
          createdAt: true,
          updatedAt: true,
          profile: {
            select: {
              profilePhotoStorageKey: true,
              homeCity: true,
              homeRegion: true,
              biography: true,
              languages: true,
              travelInterests: true,
              pastTripsVisibility: true,
              communityActivityVisibility: true,
              createdAt: true,
              updatedAt: true,
            },
          },
          authAccounts: {
            select: { provider: true, providerSubject: true, createdAt: true },
          },
          identities: {
            select: {
              type: true,
              normalizedValue: true,
              verifiedAt: true,
              createdAt: true,
            },
          },
          policyAcceptances: {
            select: { policyType: true, version: true, acceptedAt: true },
            orderBy: { acceptedAt: 'asc' },
          },
          dataRequests: {
            select: {
              id: true,
              type: true,
              status: true,
              createdAt: true,
              cancelledAt: true,
            },
            orderBy: { createdAt: 'asc' },
          },
        },
      });
      if (!account || account.status === 'DELETED') {
        throw new AppError(
          403,
          'ACCOUNT_DISABLED',
          'This account cannot be exported.',
        );
      }

      const [
        trips,
        memberships,
        sentConnectionRequests,
        receivedConnectionRequests,
        communityFollows,
        communityPosts,
        communityComments,
        conversationStates,
        checklistItems,
        expenses,
        expenseShares,
        expenseRevisions,
        expenseDisputes,
        settlements,
        messages,
        messageRevisions,
        notifications,
        blocks,
        reports,
      ] = await Promise.all([
        tx.trip.findMany({
          where: { ownerId: userId },
          select: {
            id: true,
            communityId: true,
            originCity: true,
            startDate: true,
            endDate: true,
            flexibilityDays: true,
            durationDays: true,
            budgetMin: true,
            budgetMax: true,
            currency: true,
            currentGroupSize: true,
            desiredGroupSize: true,
            transport: true,
            description: true,
            status: true,
            publishedAt: true,
            createdAt: true,
            updatedAt: true,
          },
          orderBy: { createdAt: 'asc' },
        }),
        tx.tripMembership.findMany({
          where: { userId },
          select: {
            id: true,
            tripId: true,
            connectionRequestId: true,
            role: true,
            status: true,
            joinedAt: true,
            leftAt: true,
            removedAt: true,
          },
          orderBy: { joinedAt: 'asc' },
        }),
        tx.connectionRequest.findMany({
          where: { requesterId: userId },
          select: {
            id: true,
            tripId: true,
            recipientId: true,
            relatedTripId: true,
            message: true,
            status: true,
            decidedAt: true,
            withdrawnAt: true,
            createdAt: true,
            updatedAt: true,
          },
          orderBy: { createdAt: 'asc' },
        }),
        tx.connectionRequest.findMany({
          where: { recipientId: userId },
          select: {
            id: true,
            tripId: true,
            requesterId: true,
            relatedTripId: true,
            message: true,
            status: true,
            decidedAt: true,
            withdrawnAt: true,
            createdAt: true,
            updatedAt: true,
          },
          orderBy: { createdAt: 'asc' },
        }),
        tx.communityFollow.findMany({
          where: { userId },
          select: { communityId: true, followedAt: true },
          orderBy: { followedAt: 'asc' },
        }),
        tx.communityPost.findMany({
          where: { authorId: userId },
          select: {
            id: true,
            communityId: true,
            type: true,
            status: true,
            title: true,
            body: true,
            publishedAt: true,
            editedAt: true,
            removedAt: true,
            createdAt: true,
            updatedAt: true,
          },
          orderBy: { createdAt: 'asc' },
        }),
        tx.communityComment.findMany({
          where: { authorId: userId },
          select: {
            id: true,
            postId: true,
            body: true,
            status: true,
            editedAt: true,
            removedAt: true,
            createdAt: true,
            updatedAt: true,
          },
          orderBy: { createdAt: 'asc' },
        }),
        tx.conversationParticipant.findMany({
          where: { userId },
          select: {
            conversationId: true,
            lastReadAt: true,
            mutedAt: true,
            joinedAt: true,
          },
          orderBy: { joinedAt: 'asc' },
        }),
        tx.tripChecklistItem.findMany({
          where: { OR: [{ createdById: userId }, { completedById: userId }] },
          select: {
            id: true,
            tripId: true,
            title: true,
            status: true,
            completedAt: true,
            removedAt: true,
            createdAt: true,
            updatedAt: true,
          },
          orderBy: { createdAt: 'asc' },
        }),
        tx.expense.findMany({
          where: {
            OR: [
              { createdById: userId },
              { paidById: userId },
              { shares: { some: { userId } } },
            ],
          },
          select: {
            id: true,
            tripId: true,
            createdById: true,
            paidById: true,
            description: true,
            category: true,
            amountPaise: true,
            currency: true,
            splitMethod: true,
            expenseDate: true,
            status: true,
            voidedAt: true,
            createdAt: true,
            updatedAt: true,
          },
          orderBy: { createdAt: 'asc' },
        }),
        tx.expenseShare.findMany({
          where: { userId },
          select: { expenseId: true, amountPaise: true },
          orderBy: { expenseId: 'asc' },
        }),
        tx.expenseRevision.findMany({
          where: { actorId: userId },
          select: {
            expenseId: true,
            action: true,
            version: true,
            snapshot: true,
            createdAt: true,
          },
          orderBy: { createdAt: 'asc' },
        }),
        tx.expenseDispute.findMany({
          where: { reporterId: userId },
          select: {
            id: true,
            expenseId: true,
            reason: true,
            status: true,
            withdrawnAt: true,
            createdAt: true,
            updatedAt: true,
          },
          orderBy: { createdAt: 'asc' },
        }),
        tx.settlement.findMany({
          where: { OR: [{ payerId: userId }, { receiverId: userId }] },
          select: {
            id: true,
            tripId: true,
            payerId: true,
            receiverId: true,
            amountPaise: true,
            currency: true,
            status: true,
            decidedAt: true,
            cancelledAt: true,
            createdAt: true,
            updatedAt: true,
          },
          orderBy: { createdAt: 'asc' },
        }),
        tx.message.findMany({
          where: { senderId: userId },
          select: {
            id: true,
            conversationId: true,
            body: true,
            status: true,
            editedAt: true,
            deletedAt: true,
            createdAt: true,
            updatedAt: true,
          },
          orderBy: { createdAt: 'asc' },
        }),
        tx.messageRevision.findMany({
          where: { editorId: userId },
          select: {
            messageId: true,
            action: true,
            previousBody: true,
            createdAt: true,
          },
          orderBy: { createdAt: 'asc' },
        }),
        tx.notification.findMany({
          where: { recipientId: userId },
          select: {
            id: true,
            type: true,
            sourceId: true,
            tripId: true,
            actorId: true,
            createdAt: true,
            readAt: true,
          },
          orderBy: { createdAt: 'asc' },
        }),
        tx.userBlock.findMany({
          where: { blockerId: userId },
          select: { blockedId: true, createdAt: true },
          orderBy: { createdAt: 'asc' },
        }),
        tx.report.findMany({
          where: { reporterId: userId },
          select: {
            id: true,
            targetType: true,
            reportedUserId: true,
            reportedTripId: true,
            reportedConnectionRequestId: true,
            reportedMessageId: true,
            reportedCommunityPostId: true,
            reportedCommunityCommentId: true,
            reason: true,
            details: true,
            status: true,
            createdAt: true,
            updatedAt: true,
          },
          orderBy: { createdAt: 'asc' },
        }),
      ]);

      return {
        formatVersion: 1,
        generatedAt: new Date().toISOString(),
        account,
        activity: {
          trips,
          memberships,
          sentConnectionRequests,
          receivedConnectionRequests,
          communityFollows,
          communityPosts,
          communityComments,
          conversationStates,
          checklistItems,
          expenses,
          expenseShares,
          expenseRevisions,
          expenseDisputes,
          settlements,
          messages,
          messageRevisions,
          notifications,
          blocks,
          reports,
        },
      };
    },
    {
      isolationLevel: Prisma.TransactionIsolationLevel.RepeatableRead,
      timeout: 30_000,
    },
  );
}
